{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "ad598dc5581e0417e690c7b77a6a74da", "detectedBy": ["AST_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "6dd8716deea2b55a4835b6f20cc8e9a9", "repository": "http://git.code.sf.net/p/drjava/git_repo", "fileName": "drjava/src/edu/rice/cs/drjava/model/DefaultGlobalModel.java", "commitBeforeChange": "fe10ec3049d7833e404492f382e59e4a2bb44b0e", "commitAfterChange": "ac147bfd47d7e558bfd3f0afa39ad091a35b6f6f", "methodNumberBeforeChange": 85, "methodNumberAfterChange": 81, "signatureBeforeChange": "   public void resetInteractionsClassPath()", "signatureAfterChange": "   public void resetInteractionsClassPath()", "diff": ["-          System.out.println(\"File \" + f + \" in your extra classpath could not be parsed to a URL, maybe it contains un-URL-encodable characters?\");", "+          System.out.println(\"File \" + f + \" in your extra classpath could not be parsed to a URL; \" +", "+                             \"it may contain un-URL-encodable characters.\");", "-    List<OpenDefinitionsDocument> odds = getProjectDocuments();", "+    List<OpenDefinitionsDocument> odds = getAuxiliaryDocuments();", "+    ", "+    // add project source root to projectFilesClassPath.  All files in project tree have this root.", "+    ", "+    try { _interactionsModel.addProjectFilesClassPath(getProjectRoot().toURL()); }", "+    catch(MalformedURLException murle) { /* fail silently */ } "]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "e38d7f85a9198be04979fc9573468ecb", "repository": "http://git.code.sf.net/p/drjava/git_repo", "fileName": "drjava/src/edu/rice/cs/drjava/model/GlobalModelCompileTest.java", "commitBeforeChange": "d0727a77251489c271609794ef5d58d9b3aab593", "commitAfterChange": "e782d4da2d7bff038017015047af677bda357a17", "methodNumberBeforeChange": 28, "methodNumberAfterChange": 28, "signatureBeforeChange": "   public void testOutOfSyncAfterModification()     throws BadLocationException, IOException", "signatureAfterChange": "   public void testOutOfSyncAfterModification()     throws BadLocationException, IOException", "diff": ["-    assertTrue(!doc.checkIfClassFileInSync());", "+    assertTrue(\"should not be in sync before compile\", ", "+               !doc.checkIfClassFileInSync());", "-    assertTrue(doc.checkIfClassFileInSync());", "+    assertTrue(\"should be in sync after compile\", ", "+               doc.checkIfClassFileInSync());", "-    assertTrue(!doc.checkIfClassFileInSync());", "+    assertTrue(\"should not be in sync after modification\",", "+               !doc.checkIfClassFileInSync());", "+", "+    // Have to wait 1 second so file will have a different timestamp", "+    try {", "+      Thread.sleep(1000);", "+    }", "+    catch (InterruptedException ie) {}", "+", "-    assertTrue(!doc.checkIfClassFileInSync());", "+    assertTrue(\"should not be in sync after save\", ", "+               !doc.checkIfClassFileInSync());"]}], "num": 8818}