{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "c1e636843a95ff1844bf33bcbd1d085b", "detectedBy": ["DIFF_HIERARCHICAL", "DIFF_DBSCAN", "AST_HIERARCHICAL", "AST_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "5cb13a3209d4757c51024c643ac5fff0", "repository": "https://git-wip-us.apache.org/repos/asf/ant.git", "fileName": "src/tests/junit/org/apache/tools/ant/taskdefs/optional/junit/JUnitTestRunnerTest.java", "commitBeforeChange": "ab4e0ccd0efec9967ea00c1f9538338cf3d155fd", "commitAfterChange": "3b6aedbd218dfdc3284e0ba331a686b2a8448722", "methodNumberBeforeChange": 5, "methodNumberAfterChange": 5, "signatureBeforeChange": "     public void testInvalidTestCase()", "signatureAfterChange": "     public void testInvalidTestCase()", "diff": ["-        String error = runner.getFormatter().getError();", "-        assertEquals(error, JUnitTestRunner.FAILURES, runner.getRetCode());", "+        // On junit3 this is a FAILURE, on junit4 this is an ERROR", "+        int ret = runner.getRetCode();", "+        if (ret != JUnitTestRunner.FAILURES && ret != JUnitTestRunner.ERRORS) {", "+            fail(\"Unexpected result \" + ret + \" from junit runner\");", "+        }", "+        // JUNIT3 test", "+        //assertEquals(error, JUnitTestRunner.FAILURES, runner.getRetCode());"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "5ccad35f4f5a8ba539b512f0be0d6048", "repository": "https://git-wip-us.apache.org/repos/asf/ant.git", "fileName": "src/tests/junit/org/apache/tools/ant/taskdefs/optional/junit/JUnitTestRunnerTest.java", "commitBeforeChange": "ab4e0ccd0efec9967ea00c1f9538338cf3d155fd", "commitAfterChange": "3b6aedbd218dfdc3284e0ba331a686b2a8448722", "methodNumberBeforeChange": 4, "methodNumberAfterChange": 4, "signatureBeforeChange": "     public void testNoTestCase()", "signatureAfterChange": "     public void testNoTestCase()", "diff": ["-        assertEquals(runner.getFormatter().getError(), JUnitTestRunner.FAILURES, runner.getRetCode());", "+        // On junit3 this is a FAILURE, on junit4 this is an ERROR", "+        int ret = runner.getRetCode();", "+        ", "+        if (ret != JUnitTestRunner.FAILURES && ret != JUnitTestRunner.ERRORS) {", "+            fail(\"Unexpected result \" + ret + \" from junit runner\");", "+        }", "+        // JUnit3 test", "+        //assertEquals(runner.getFormatter().getError(), JUnitTestRunner.FAILURES, runner.getRetCode());"]}]}