{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "1f28bbf922cc0ef7e5e39433be7127b6", "detectedBy": ["DIFF_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "02e8b8844208142c3cd5a56ac44595b4", "repository": "http://git.eclipse.org/gitroot/jdt/eclipse.jdt.core.git", "fileName": "org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/ProgrammingProblemsTest.java", "commitBeforeChange": "d0c29ef085aca7621ab6ac19e8de871cbd734495", "commitAfterChange": "c8ca33a12ce5373c4c6bcb65eced790d82bc1944", "methodNumberBeforeChange": 40, "methodNumberAfterChange": 36, "signatureBeforeChange": " public void test0035_declared_thrown_unchecked_exceptions()", "signatureAfterChange": " public void test0032_declared_thrown_checked_exceptions()", "diff": ["-public void test0035_declared_thrown_unchecked_exceptions() {", "+// suppressed the warning for unchecked exceptions", "+public void test0032_declared_thrown_checked_exceptions() {", "-\tcustomOptions.put(CompilerOptions.OPTION_ReportUnusedDeclaredThrownExceptionIncludeUncheckedExceptions, ", "-\t\t\tCompilerOptions.ENABLED);", "+\tcustomOptions.put(CompilerOptions.OPTION_ReportUnusedDeclaredThrownExceptionExemptExceptionAndThrowable, ", "+\t\t\tCompilerOptions.DISABLED);", "-\t\t\"----------\\n\" + ", "-\t\t\"1. WARNING in X.java (at line 2)\\n\" + ", "-\t\t\"\tpublic void foo() throws Error {\\n\" + ", "-\t\t\"\t                         ^^^^^\\n\" + ", "-\t\t\"The declared exception Error is not actually thrown by the method foo() from type X\\n\" + ", "-\t\t\"----------\\n\" /* expectedCompilerLog */,", "+\t\t\"\" /* expectedCompilerLog */,"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "9a8fedaa2e8481330500c301549a6fd3", "repository": "http://git.eclipse.org/gitroot/jdt/eclipse.jdt.core.git", "fileName": "org.eclipse.jdt.core.tests.compiler/src/org/eclipse/jdt/core/tests/compiler/regression/ProgrammingProblemsTest.java", "commitBeforeChange": "d0c29ef085aca7621ab6ac19e8de871cbd734495", "commitAfterChange": "c8ca33a12ce5373c4c6bcb65eced790d82bc1944", "methodNumberBeforeChange": 37, "methodNumberAfterChange": 33, "signatureBeforeChange": " public void test0032_declared_thrown_unchecked_exceptions()", "signatureAfterChange": " public void test0029_declared_thrown_checked_exceptions()", "diff": ["-public void test0032_declared_thrown_unchecked_exceptions() {", "+// suppressed the warning for unchecked exceptions, using Exception instead", "+public void test0029_declared_thrown_checked_exceptions() {", "-\t\tcustomOptions.put(CompilerOptions.OPTION_ReportUnusedDeclaredThrownExceptionIncludeUncheckedExceptions, ", "-\t\t\t\tCompilerOptions.ENABLED);", "+\t\tcustomOptions.put(CompilerOptions.OPTION_ReportUnusedDeclaredThrownExceptionExemptExceptionAndThrowable, ", "+\t\t\t\tCompilerOptions.DISABLED);", "-\t\t\t\t\"  public void foo() throws ArithmeticException {\\n\" + ", "+\t\t\t\t\"  public void foo() throws Exception {\\n\" + "]}], "num": 64303}