{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "1d81edd580c8873d17681b7b7d1268d9", "detectedBy": ["AST_HIERARCHICAL", "AST_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "21f9a3a90c25cc4211414cf7c3974022", "repository": "https://git-wip-us.apache.org/repos/asf/ant.git", "fileName": "src/main/org/apache/tools/ant/Main.java", "commitBeforeChange": "98caa52a0a2816697e533f7864a95b52e293273f", "commitAfterChange": "99529fd6c5e0d622048fe2ea34af150b7a1f09ff", "methodNumberBeforeChange": 19, "methodNumberAfterChange": 19, "signatureBeforeChange": "     private void runBuild(ClassLoader coreLoader) throws BuildException", "signatureAfterChange": "     private void runBuild(ClassLoader coreLoader) throws BuildException", "diff": ["-                project.fireBuildFinished(error);", "+                try {", "+                    project.fireBuildFinished(error);", "+                } catch (Throwable t) {", "+                    // yes, I know it is bad style to catch Throwable,", "+                    // but if we don't, we lose valuable information", "+                    System.err.println(\"Caught an exception while logging the\"", "+                                       + \" end of the build.  Exception was:\");", "+                    t.printStackTrace();", "+                    if (error != null) {", "+                        System.err.println(\"There has been an error prior to\"", "+                                           + \" that:\");", "+                        error.printStackTrace();", "+                    }", "+                    throw new BuildException(t);", "+                }"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "25d2cb514ef3546a1cb43706bbaa55b2", "repository": "https://git-wip-us.apache.org/repos/asf/ant.git", "fileName": "src/tests/junit/org/apache/tools/ant/taskdefs/optional/junit/JUnitTaskTest.java", "commitBeforeChange": "521890b4299b52da126e78d4d1e0974bd7db1712", "commitAfterChange": "8542d84b4b941a882b83918589fba32d73f98538", "methodNumberBeforeChange": 11, "methodNumberAfterChange": 11, "signatureBeforeChange": "     public void testFailureRecorder()", "signatureAfterChange": "     public void testFailureRecorder()", "diff": ["+        try {", "+        } catch (BuildException be) {", "+            be.printStackTrace();", "+            System.err.println(\"nested build's log: \" + getLog());", "+            System.err.println(\"nested build's System.out: \" + getOutput());", "+            System.err.println(\"nested build's System.err: \" + getError());", "+            fail(\"Ant execution failed: \" + be.getMessage());", "+        }"]}]}