{"@class": "de.fau.cs.inf2.cthree.data.Cluster", "id": "2a29c4d662be280882dabe944fb0b3e2", "detectedBy": ["AST_HIERARCHICAL", "AST_DBSCAN"], "members": [{"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "5efc57ee6d237435c3799667e59f366a", "repository": "https://github.com/junit-team/junit.git", "fileName": "src/main/java/org/junit/runner/JUnitCore.java", "commitBeforeChange": "74f32863f4ec20f015bd3b1a4300c93a69ce98ba", "commitAfterChange": "196c4ed79cbaca37709643b54913b361b677ae04", "methodNumberBeforeChange": 3, "methodNumberAfterChange": 3, "signatureBeforeChange": "     public static Result runClasses(Class<?>... classes)", "signatureAfterChange": "     public static Result runClasses(Class<?>... classes)", "diff": ["-        return new JUnitCore().run(defaultComputer(), classes);", "+        return runClasses(defaultComputer(), classes);"]}, {"@class": "de.fau.cs.inf2.cthree.data.CodeChange", "id": "ad3a000fadea60eb07097fd4fd40f6db", "repository": "https://github.com/junit-team/junit.git", "fileName": "src/test/java/org/junit/tests/experimental/rules/ExpectedExceptionRuleTest.java", "commitBeforeChange": "052fc095d5b4a8af643d0e4402a504716ad8eb03", "commitAfterChange": "231241782c199d39943f742d0abe57057b0b785c", "methodNumberBeforeChange": 6, "methodNumberAfterChange": 6, "signatureBeforeChange": " \t \t@Test \tpublic void expectedExceptionClauseExists()", "signatureAfterChange": " \t \t@Test \tpublic void expectedExceptionClauseExists()", "diff": ["-\t\tassertThat(new JUnitCore().run(HasWrongExpectedException.class),", "+\t\tassertThat(", "+\t\t\t\ttestResult(HasWrongExpectedException.class),", "-\t}\t", "+\t}"]}]}